# Generated by Django 5.2.9 on 2025-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='total_tracks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
